### ISSUE TITLE
Error: spawnSync C:\Windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by webmandman** [nxpm/stack#142]
## Expected Behavior

Initialize my first PANNG stack test app.

## Current Behavior

When I run nxpm-stack init --name sandbox I get this error:

```
>  NXPM  Creating Nx Workspace
>  NXPM   RUN  yarn create nx-workspace PANNGstackTestApp --cli=nx --nx-cloud=false --preset=empty --skip-install --package-manager=yarn
>  NXPM  Install dependencies
>  NXPM   RUN  yarn add -D @nxpm/stack @nrwl/angular @nrwl/nest @nxtend/ionic-angular @nxtend/capacitor @ngneat/tailwind@5.2.4
nxpm-stack.js init

Initialize new nxpm workspace

Options:
      --help             Show help                                     [boolean]
      --version          Show version number                           [boolean]
      --allowExisting                                                  [boolean]
  -n, --name                                                 [string] [required]
      --cli                                             [string] [default: "nx"]
      --webStyleLibrary                           [string] [default: "tailwind"]

<ref *1> Error: spawnSync C:\Windows\system32\cmd.exe ENOENT
    at Object.spawnSync (internal/child_process.js:1066:20)
    at spawnSync (child_process.js:602:24)
    at Object.execSync (child_process.js:647:15)
    at runCommand (C:\Development\Tools\nvm\v14.11.0\node_modules\@nxpm\cli\src\lib\commands\workspace-init.js:15:21)
    at Object.<anonymous> (C:\Development\Tools\nvm\v14.11.0\node_modules\@nxpm\cli\src\lib\commands\workspace-init.js:60:9)
    at Generator.next (<anonymous>)
    at C:\Development\Tools\nvm\v14.11.0\node_modules\@nxpm\cli\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Development\Tools\nvm\v14.11.0\node_modules\@nxpm\cli\node_modules\tslib\tslib.js:113:16)
    at Object.workspaceInit (C:\Development\Tools\nvm\v14.11.0\node_modules\@nxpm\cli\src\lib\commands\workspace-init.js:38:20) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs: [
    '/d',
    '/s',
    '/c',
    '"yarn add -D @nxpm/stack @nrwl/angular @nrwl/nest @nxtend/ionic-angular @nxtend/capacitor @ngneat/tailwind@5.2.4"'
  ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

## Steps to Reproduce (for bugs)

1. `npm i  -g #nxpm/cli `
2. `nxpm-stack init --name sandbox`

## Your Environment

- OS: Windows 10 64-bit

I tried it using CMD and Cmder.

**Comment by webmandman** [comment]
Should I use a newer version of NPM?

**Comment by beeman** [comment]
Hey there @webmandman - thanks for checking out nxpm-stack!

Currently, the `nxpm-stack` installer depends on having `yarn` v1.x installed. Do you have that running?

**Comment by webmandman** [comment]
Hello Beeman, yes I have 1.22.10.
