### ISSUE TITLE
Error creating a new project using @nxpm/cli: Required property 'name' is missing

### ISSUE THREAD

**Issue by jannie-louwrens** [nxpm/stack#155]
## Expected Behavior

Creating a new workspace using `nxpm-stack init --name sandbox` should work.

## Current Behavior

It fails with the error message `Required property 'name' is missing`:
```
jannie-desktop:nxpm-stack$ nxpm-stack init --name sandbox
>  NXPM  Creating Nx Workspace
>  NXPM   RUN  yarn create nx-workspace sandbox --cli=nx --nx-cloud=false --preset=empty --skip-install --package-manager=yarn --default-base=main   
>  NXPM  Install dependencies
>  NXPM   RUN  yarn add -D @nxpm/stack@latest @nrwl/angular @nrwl/nest @nxtend/ionic-angular@beta @nxtend/capacitor@beta
>  NXPM  Initialize @nxpm/stack
>  NXPM   RUN  yarn nx g @nxpm/stack:init 
nxpm-stack.js init

Initialize new nxpm workspace

Options:
      --help             Show help                                     [boolean]
      --version          Show version number                           [boolean]
      --allowExisting                                                  [boolean]
      --tag                                         [string] [default: "latest"]
  -n, --name                                                 [string] [required]
      --cli                                             [string] [default: "nx"]
      --skipApi                                                        [boolean]
      --skipMobile                                                     [boolean]
      --skipWeb                                                        [boolean]
      --webStyleLibrary                           [string] [default: "tailwind"]

Error: Command failed: yarn nx g @nxpm/stack:init 
Required property 'name' is missing
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at runCommand (/home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/@nxpm+cli@5.0.0-beta.17/node_modules/@nxpm/cli/src/lib/commands/workspace-init.js:14:34)
    at /home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/@nxpm+cli@5.0.0-beta.17/node_modules/@nxpm/cli/src/lib/commands/workspace-init.js:48:9
    at Generator.next (<anonymous>)
    at /home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:113:16)
    at workspaceInit (/home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/@nxpm+cli@5.0.0-beta.17/node_modules/@nxpm/cli/src/lib/commands/workspace-init.js:20:34)
    at /home/jannie/.npm-global/pnpm-global/5/node_modules/.pnpm/@nxpm+cli@5.0.0-beta.17/node_modules/@nxpm/cli/src/lib/cli.js:47:46 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 32 32 2e 31 37 0a 24 20 2f 68 6f 6d 65 2f 6a 61 6e 6e 69 65 2f 70 72 6f 6a 65 63 74 73 2f 6e 78 70 6d 2d 73 74 61 ... 136 more bytes>,
    <Buffer 52 65 71 75 69 72 65 64 20 70 72 6f 70 65 72 74 79 20 27 6e 61 6d 65 27 20 69 73 20 6d 69 73 73 69 6e 67 0a 65 72 72 6f 72 20 43 6f 6d 6d 61 6e 64 20 ... 25 more bytes>
  ],
  pid: 7934,
  stdout: <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 32 32 2e 31 37 0a 24 20 2f 68 6f 6d 65 2f 6a 61 6e 6e 69 65 2f 70 72 6f 6a 65 63 74 73 2f 6e 78 70 6d 2d 73 74 61 ... 136 more bytes>,
  stderr: <Buffer 52 65 71 75 69 72 65 64 20 70 72 6f 70 65 72 74 79 20 27 6e 61 6d 65 27 20 69 73 20 6d 69 73 73 69 6e 67 0a 65 72 72 6f 72 20 43 6f 6d 6d 61 6e 64 20 ... 25 more bytes>
}
```

## Your Environment

- Version used: `@nxpm/cli 5.0.0-beta.17`
- Angular Version: `Angular CLI: 13.1.4`
- Node Version: `16.13.2`
- NPM  Version: `8.3.2`
- PNPM Version: `6.27.2`
- Yarn Version: `1.22.17`
- NX Version: `nx 13.4.6`
- Operating System and version (desktop or mobile): `Linux Mint 20.3 Cinnamon v.5.2.7 Kernel v.5.4.0-96-generic`

**Comment by beeman** [comment]
@jannie-louwrens thanks for creating this issue, I'm out this weekend but will look at it when I'm back.
